// Manual-only customer catalog controls. Data is stored in Supabase.
let catalogMetadata = new Map(), catalogBusyIds = new Set(), catalogLoaded = false, catalogLoadBusy = false, catalogManualId = null, catalogManualBusy = false;
const catalogConditions = ['7/10', '8/10', '9/10', 'Як новий'];
function catalogEligibleLaptops(){ return laptops.filter(item => normalizeStatus(item.status) === 'received' && normalizeLocationState(item.location_state) !== 'Ремонт' && !isTestLaptop(item)); }
function catalogMessage(message){ const status = document.getElementById('catalogAdminStatus'); status.textContent = message; status.hidden = !message; }
function catalogMissingFields(meta = {}){
  return Object.entries({title:'назва',processor:'процесор',ram:'ОЗУ',ssd:'SSD',condition:'стан',price:'ціна'})
    .filter(([key]) => !String(meta[key] ?? '').trim()).map(([,label]) => label);
}
function renderCatalogAdmin(){
  const list = document.getElementById('catalogAdminList'); if(!list || !document.getElementById('view-catalog-admin').classList.contains('active')) return;
  const summary = document.getElementById('catalogMissingNumbers');
  if(!catalogLoaded){ list.replaceChildren(); summary.replaceChildren(); summary.hidden = true; return; }
  const items = catalogEligibleLaptops();
  const missingItems = items.filter(item => catalogMissingFields(catalogMetadata.get(String(item.id))).length);
  summary.hidden = !missingItems.length;
  summary.innerHTML = missingItems.length ? `<span class="muted">Не заповнено:</span><div class="catalog-number-buttons">${missingItems.map(item => `<button type="button" class="ghost" data-catalog-missing-id="${safe(item.id)}" aria-label="Заповнити дані ноутбука № ${safe(item.number)}">${safe(item.number)}</button>`).join('')}</div>` : '';
  list.innerHTML = items.length ? items.map(item => {
    const meta = catalogMetadata.get(String(item.id)) || {};
    const busy = catalogBusyIds.has(String(item.id));
    const missing = catalogMissingFields(meta);
    const heading = `<div class="catalog-admin-heading"><span class="muted">Ноутбук № ${safe(item.number)}</span><span class="catalog-available">Отримано</span></div><h3>${safe(meta.title || 'Назва не вказана')}</h3>`;
    const content = `<p class="muted catalog-admin-processor">Процесор: ${safe(meta.processor || 'Не вказано')}</p><dl class="catalog-admin-specs"><div><dt>Оперативна пам’ять</dt><dd>${safe(meta.ram || 'Не вказано')}</dd></div><div><dt>SSD</dt><dd>${safe(meta.ssd || 'Не вказано')}</dd></div><div><dt>Стан</dt><dd>${safe(meta.condition || 'Не вказано')}</dd></div><div><dt>Ціна</dt><dd>${safe(meta.price || 'Не вказано')}</dd></div></dl>${missing.length ? `<p class="catalog-completion is-missing">Не заповнено: ${safe(missing.join(', '))}</p>` : ''}<button class="ghost" type="button" data-catalog-manual ${busy ? 'disabled' : ''}>Редагувати</button>`;
    return `<article class="catalog-admin-card" data-catalog-id="${safe(item.id)}">${missing.length ? heading + content : `<details class="catalog-admin-details"><summary>${heading}<span class="catalog-admin-toggle"><span class="catalog-show-details">Показати деталі</span><span class="catalog-hide-details">Згорнути</span><span class="catalog-admin-chevron" aria-hidden="true">⌄</span></span></summary>${content}</details>`}</article>`;
  }).join('') : '<div class="empty">Немає отриманих ноутбуків без ремонту.</div>';
}
async function loadCatalogAdmin(){
  if(catalogLoadBusy) return; catalogLoadBusy = true; catalogLoaded = false; renderCatalogAdmin(); catalogMessage('Завантаження каталогу…');
  try { const { data, error } = await supabaseClient.from('laptop_catalog').select('*').abortSignal(AbortSignal.timeout(REQUEST_TIMEOUT_MS)); if(error) throw new Error('Не вдалося завантажити каталог. Перевір налаштування Supabase.'); catalogMetadata = new Map((data || []).map(row => [String(row.laptop_id), row])); catalogLoaded = true; catalogMessage(''); }
  catch(error){ catalogMessage(error.message); } finally { catalogLoadBusy = false; renderCatalogAdmin(); }
}
async function saveCatalogMetadata(id, patch){ const { data, error } = await supabaseClient.from('laptop_catalog').upsert({ laptop_id:String(id), ...patch }, { onConflict:'laptop_id' }).select('*').abortSignal(AbortSignal.timeout(REQUEST_TIMEOUT_MS)); if(error || !data?.length) throw new Error('Не вдалося зберегти в Supabase. Повтори спробу.'); catalogMetadata.set(String(id), data[0]); }
function openCatalogManual(id){ const item = catalogEligibleLaptops().find(item => String(item.id) === id); if(!catalogLoaded || !item) return; const meta = catalogMetadata.get(id) || {}; const match = String(meta.title || '').match(/^(HP (?:Elitebook|Probook|Zbook))\s*(.*)$/i); catalogManualId = id; document.getElementById('catalogManual-brand').value = match ? match[1].replace(/elitebook/i,'Elitebook').replace(/probook/i,'Probook').replace(/zbook/i,'Zbook') : ''; document.getElementById('catalogManual-generation').value = (String(meta.title || '').match(/\bG[3-8]\b/i)?.[0] || '').toUpperCase(); document.getElementById('catalogManual-ram').value = /^(16|32)(?:\s*(?:ГБ|GB))?$/i.test(String(meta.ram || '').trim()) ? `${parseInt(meta.ram, 10)} ГБ` : ''; const ssd = String(meta.ssd || '').trim(); document.getElementById('catalogManual-ssd').value = /^(256|512|1024)(?:\s*(?:ГБ|GB))?$/i.test(ssd) ? `${parseInt(ssd, 10)} ГБ` : /^1\s*(?:ТБ|TB)$/i.test(ssd) ? '1024 ГБ' : ''; for(const field of ['price','condition','processor']) document.getElementById(`catalogManual-${field}`).value = meta[field] || ''; document.getElementById('catalogManual-generation').setCustomValidity(''); document.getElementById('catalogManualTitle').textContent = `Ноутбук № ${item.number} — дані для покупця`; document.getElementById('catalogManualStatus').textContent = ''; document.getElementById('catalogManualModal').showModal(); document.getElementById('catalogManual-brand').focus(); }
function closeCatalogManual(){ if(catalogManualBusy) return; document.getElementById('catalogManualModal').close(); catalogManualId = null; }
async function saveCatalogManual(event){ event.preventDefault(); if(catalogManualBusy || !catalogManualId) return; const item = catalogEligibleLaptops().find(item => String(item.id) === catalogManualId); const status = document.getElementById('catalogManualStatus'); if(!item){ status.textContent = 'Ноутбук більше не доступний у каталозі.'; return; } const brand = document.getElementById('catalogManual-brand'); const generation = document.getElementById('catalogManual-generation'); generation.setCustomValidity(generation.value.trim() ? '' : 'Обери покоління.'); if(!document.getElementById('catalogManualForm').reportValidity()) return; catalogManualBusy = true; const savingId = catalogManualId; const submit = document.querySelector('#catalogManualForm button[type=submit]'); submit.disabled = true; catalogBusyIds.add(savingId); status.textContent = 'Збереження…'; try { await saveCatalogMetadata(catalogManualId, { title:`${brand.value} ${generation.value.trim()}`, ram:document.getElementById('catalogManual-ram').value.trim() || null, ssd:document.getElementById('catalogManual-ssd').value.trim() || null, price:document.getElementById('catalogManual-price').value.trim() || null, condition:document.getElementById('catalogManual-condition').value || null, processor:document.getElementById('catalogManual-processor').value || null }); catalogMessage(''); catalogManualBusy = false; closeCatalogManual(); } catch(error){ status.textContent = error.message; } finally { catalogBusyIds.delete(savingId); catalogManualBusy = false; submit.disabled = false; renderCatalogAdmin(); } }
function resetCatalogAdmin(){ catalogLoaded = false; catalogMetadata.clear(); }
document.addEventListener('DOMContentLoaded', () => { document.getElementById('catalogMissingNumbers').addEventListener('click', event => { const button = event.target.closest('[data-catalog-missing-id]'); if(button) openCatalogManual(button.dataset.catalogMissingId); }); document.getElementById('catalogManualForm').addEventListener('submit', saveCatalogManual); document.getElementById('catalogManual-generation').addEventListener('input', event => event.target.setCustomValidity('')); document.getElementById('catalogManualClose').addEventListener('click', closeCatalogManual); document.getElementById('catalogManualModal').addEventListener('cancel', event => { event.preventDefault(); closeCatalogManual(); }); document.getElementById('catalogPublicLink').href = new URL('catalog.html', location.href).href; document.getElementById('catalogAdminList').addEventListener('click', event => { const button = event.target.closest('[data-catalog-manual]'); if(button) openCatalogManual(button.closest('[data-catalog-id]').dataset.catalogId); }); });
